spring:
  webflux:
    base-path: /api
  application:
    name: oxatrade-service
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE # configure the whole application to expect the snake case input
  #autoconfigure:
    # To discard the security auto-configuration and add our own configuration:
    #exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  
  security:
    oauth2: 
      client:
        registration:
          # OAuth 2.0-Google-Client
          # https://console.cloud.google.com/apis/credentials
          google:
            client-id: ${OAUTH2_GOOGLE_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - openid
          # OAuth 2.0-Facebook-Client
          # https://developers.facebook.com/apps/
          facebook:
            client-id: ${OAUTH2_FACEBOOK_ID}
            client-secret: ${OAUTH2_FACEBOOK_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - email

server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false
    
# custom:
oxa:
  # see: https://randomkeygen.com/
  jwt:
    password:
      encoder:
        secret: ${JWT_PASS_SECRET} # Run -> Run Config. -> Environment
        iteration: 64
        keylength: 256
    secret: ${JWT_SECRET}
    expiration: 3600 # in seconds 1 hour
    issuer: nosetr # organisation
  
# see: https://springdoc.org/#properties
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    # swagger-ui custom path:
    path: /swagger
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
  api-docs:
    # /api-docs endpoint custom path
    path: /api-docs
    # In order to disable the springdoc-openapi endpoint (/v3/api-docs by default):
    #enabled: false
  # Boolean. To enable spring-security support:
  enable-spring-security: true


