spring:
  application:
    name: oxatrade-service
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE # configure the whole application to expect the snake case input
  config:
    import: 
      - classpath:config/db.yml
      - classpath:config/oxa.yml
  #autoconfigure:
    # To discard the security auto-configuration and add our own configuration:
    #exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
     #For file upload:
     max-file-size: 100MB
     max-request-size: 100MB

server:
  port: 8083
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
     

logging:
  config: classpath:config/logback-spring.xml
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG # INFO, WARN, or ERROR

# see: https://springdoc.org/#properties
springdoc:
  #webjars:
    #prefix:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    # swagger-ui custom path:
    path: /swagger
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
    # In order to disable the swagger-ui:
    #enabled: false
  api-docs:
    # /api-docs endpoint custom path
    path: /api-docs
    # In order to disable the springdoc-openapi endpoint (/v3/api-docs by default):
    #enabled: false
  # Boolean. To enable spring-security support:
  enable-spring-security: true

---
spring:
  config:
    activate:
      on-profile: test
      
  sql:
    init:
        mode: never

server:
  port: 8083
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    

springdoc:
  swagger-ui:
    enabled: false
