spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade_webflux?allowPublicKeyRetrieval=true&useSSL=false
    username: oxatrade
    password: 12345678
    # Spec. for file "MySQLConfiguration"
    host: ${MYSQL_HOST:localhost}
    port: 3306
    driver: mysql
    database: oxatrade_webflux
    
  flyway:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade_webflux?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

---
spring:
  config:
    activate:
      on-profile: test
      
  application:
    name: oxatrade-test
  r2dbc:
    #url: r2dbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade_test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    #username: oxatrade
    #password: 12345678
    url: r2dbc:tc:postgresql:///testdb?TC_IMAGE_TAG=16-alpine
  flyway:
    enabled: false

server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    

springdoc:
  swagger-ui:
    enabled: false
    
    
    