# custom:
oxatrade:
  # see: https://randomkeygen.com/
  jwt:
    password:
      encoder:
        secret: ${JWT_PASS_SECRET} # Run -> Run Config. -> Environment
        iteration: 64
        keylength: 256
    secret: ${JWT_SECRET}
    expiration: 3600 # in seconds 1 hour
    issuer: nosetr # organisation
  # Mail templates directory inside main/resources or absolute filesystem path 
  mail:
    templates:
      path: mail-templates
      
---
spring:
  config:
    activate:
      on-profile: dev
      
# custom:
oxatrade:
  cors:
    allowedOrigins: http://localhost:5173,http://localhost:8080