spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade?allowPublicKeyRetrieval=true&useSSL=false
    username: oxatrade
    password: 12345678
    # Spec. for file "MySQLConfiguration"
    host: ${MYSQL_HOST:localhost}
    port: 3306
    driver: mysql
    database: oxatrade
    
  flyway:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    
  jpa:
    hibernate:
      ddl-auto: create # only for development

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:h2:file:///./tmp/test-db
    name: sa
    password:
  flyway:
    url: jdbc:h2:file:///./tmp/test-db;DB_CLOSE_DELAY=-1
    #locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    schemas: PUBLIC # H2 default schema for test databases