spring:
  application:
    name: oxatrade-service
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE # configure the whole application to expect the snake case input
  config:
    import: 
      - db.yml
      - oxa.yml
  #autoconfigure:
    # To discard the security auto-configuration and add our own configuration:
    #exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
     #For file upload:
     max-file-size: 100MB
     max-request-size: 100MB

server:
  port: 8083
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: test

server:
  port: 8083
